### ISSUE TITLE
Proposing to deprecate this project

### ISSUE THREAD

**Issue by ktoso** [lightbend/service-locator-dns#21]
Once we make sure everyone using it has an alternative or way forward this project should likely be deprecated. I've found it makes much assumptions and is a bit weird, while using the raw DNS things isn't actually all that difficult to begin with.

Just a proposal for now, since I noticed I had to back out of using it and use raw things anyway.

**Comment by huntc** [comment]
Can you point to how you'd perform a DNS SRV lookup alternatively? DNS SRV lookups involve multiple steps which is what this library captures as per https://github.com/lightbend/service-locator-dns/blob/master/service-locator-dns/src/main/scala/com/lightbend/dns/locator/ServiceLocator.scala

**Comment by ktoso** [comment]
Yes, I've read the code ;-)
Doing it somewhat simple and also having it in the codebase I actively maintain makes sense.

Other than personal affection to this project, why keep it here?

**Comment by huntc** [comment]
> Doing it somewhat simpler and also having it in the codebase I actively maintain makes sense.

I agree completely. However, I didn't infer this in the original comment given, "while using the raw DNS things isn't actually all that difficult to begin with". If you're going to capture the multiple steps of a DNS SRV lookup within Akka core itself then that'd be wonderful.

> Other than personal affection to this project, why keep it here?

I have no personal ties to this project. Please refrain from personal comments.

**Comment by ktoso** [comment]
Sorry for assuming the personal ties there.

So far I think this will move to akka-management, which will be OSS and handle things like joining.
We'll see if it needs to move into real core, it could maybe -- we'll see if others need it as well (talking to other teams now)

**Comment by huntc** [comment]
Sounds great. Makes sense then to deprecate. Thanks for the dialogue.

**Comment by sidthesloth** [comment]
Hi 

I'm trying to make use of the Pure Akka usage of the service-locator-dns in a play application that is acting as my api gateway that clients connect to and intern the gateway routes the requests to Lagom services managed in kubernates clusters. given the above comments is it still appropriate to use it and can someone point me to a working example so I can see how its configured? Thanks in advance

**Comment by kolemannix** [comment]
I am in the process of getting my Lagom suite of services ready for production and am deciding whether to use Consul's service API or Consul's DNS API for service location. The latter would mean using this plugin and remaining agnostic to the actual service provider. I like the idea of this, but am unsure of the state of this project.

I see some activity for Lagom 1.4 compatibility ( #28 ), but I do not want to commit to this library if it will not be maintained.

**Comment by TimMoore** [comment]
@mitkus / @dbrinegar is this project now completely replaced by `reactive-lib`, or are there still some situations where you might prefer to use this version instead?

**Comment by dbrinegar** [comment]
not aware of anything that might still need this one

**Comment by dbrinegar** [comment]
@kolemannix sorry we didn't get back to your question last month.  Our thinking is to use akka-management and reactive-lib for this layer, which means should be able to use dns mechanism still but using these other libs.

**Comment by TimMoore** [comment]
Can we update the project description, URL and `README.md` to make it clear that this project is obsolete and point to the Lightbend Orchestration documentation?

**Comment by ktoso** [comment]
> I am in the process of getting my Lagom suite of services ready for production and am deciding whether to use Consul's service API or Consul's DNS API for service location. 

For reference: The general direction is likely to implement the actual lookups in akka-discovery, over here, where a community member is currently contributing an consul integration: https://github.com/akka/akka-management/pull/202 With those in place, we can make Lagom's service discovery utilise those lower level implementations inside Lagom I believe.

> Can we update the project description, URL and README.md to make it clear that this project is obsolete and point to the Lightbend Orchestration documentation?

And likely put it in archive mode; ping me if unsure how to do that or something.

**Comment by dbrinegar** [comment]
done
