### ISSUE TITLE
Publish the Scala 2.12 version

### ISSUE THREAD

**Issue by guizmaii** [lightbend/service-locator-dns#24]
Hi,

It seems that the Scala 2.12 version of this lib is not yet published into Maven: https://mvnrepository.com/artifact/com.lightbend/lagom14-scala-service-locator-dns

Is it possible to publish it please ?

Regards,
Jules

**Comment by longshorej** [comment]
They're on the way - should be synced to Maven Central in the next 30m or so.

**Comment by guizmaii** [comment]
Thanks a lot !

**Comment by TimMoore** [comment]
Thanks both of you @guizmaii and @longshorej!
